---

- name: "Copy {{ cni.name }} network config"
  template: src="{{ cni.template.config }}.j2" dest={{ kube_network_dir }}/{{ cni.template.config }}
  run_once: true
  delegate_to: "{{ groups['etcd'][0] }}"

- name: Load the Flannel network config into Etcd (http)
  when: etcd_peer_url_scheme == 'http'
  shell: |
    /usr/bin/etcdctl --no-sync \
                     --peers={{ etcd_endpoints }} \
                     set {{ conf_loc }} < {{ kube_network_dir }}/{{ cni.template.config }}
  run_once: true
  delegate_to: "{{ groups['etcd'][0] }}"

- name: Load the Flannel network config into Etcd (https)
  when: etcd_peer_url_scheme == 'https'
  shell: |
    /usr/bin/etcdctl --cert-file={{ etcd_peer_cert_file }} \
                     --ca-file={{ etcd_peer_ca_file }} \
                     --key-file={{ etcd_peer_key_file }} \
                     --no-sync \
                     --peers={{ etcd_endpoints }} \
                     set {{ conf_loc }} < {{ kube_network_dir }}/{{ cni.template.config }}
  run_once: true
  delegate_to: "{{ groups['etcd'][0] }}"
