---
# Require the cluster is fully operation and running
- hosts: cluster
  become: yes
  roles:
    - { role: ceph, tags: ceph }

- hosts: masters
  become: yes
  roles:
    - { role: ceph-k8s, tags: ceph-k8s }
