---
- hosts: all
  roles:
    - commons
  tags:
    - commons

# install ssl cert
- hosts: sslhost
  roles:
     -  sslcert
  tags:
     -  sslcert

# Install etcd
- hosts: etcd
  roles:
   -   etcd
  tags:
    - etcd

# Install flannel
- hosts: all
  roles:
   - flannel
  tags:
    - flannel

# Install docker
- hosts: all
  roles:
    - docker
  tags:
    - docker

# install vip-haproxy
- hosts: masters
  roles:
    - vip-haproxy
  tags:
    - vip-haproxy

# install kubernetes master
- hosts: masters
  roles:
    - master
  tags:
    - master

# install kubernetes nodes
- hosts: nodes
  roles:
    - node
  tags:
    - node
