---
- hosts: all
  roles:
    - commons
  tags:
    - commons

- hosts: sslhost
  roles:
     -  sslcert
  tags:
     -  sslcert

- hosts: etcd
  roles:
   -   etcd
  tags:
    - etcd

- hosts: all
  roles:
   - flannel
  tags:
    - flannel

- hosts: all
  roles:
    - docker
  tags:
    - docker

- hosts: masters
  roles:
    - ha
  tags:
    - ha

- hosts: masters
  roles:
    - master
  tags:
    - master

# - hosts: nodes
#   roles:
#     - node
#   tags:
#     - node
