---
# Deploy a kubernetes cluster.

- hosts: sslhost
  become: yes
  roles:
    - { role: sslcert, tags: sslcert }

- hosts: etcd
  become: yes
  roles:
   - { role: etcd, tags: etcd }

- hosts: cluster
  become: yes
  roles:
    - { role: docker, tags: docker }

- hosts: cluster
  become: yes
  roles:
   - { role: networking/flannel, when: networking == 'flannel', tags: flannel }

- hosts: masters
  become: yes
  roles:
    - { role: kubernetes/ha, tags: ha }
    - { role: kubernetes/master, tags: master }

- hosts: nodes
  become: yes
  roles:
    - { role: kubernetes/node, tags: node }

- hosts: cluster
  become: yes
  roles:
   - { role: networking/calico, when: networking == 'calico', tags: calico }
