---
# Deploy a kubernetes cluster.

- hosts: sslhost
  gather_facts: no
  become: yes
  roles:
    - { role: sslcert, tags: sslcert }

- hosts: etcd
  become: yes
  roles:
   - { role: etcd, tags: etcd }

- hosts: cluster
  gather_facts: no
  become: yes
  roles:
    - { role: docker, tags: docker }

- hosts: cluster
  become: yes
  roles:
   - { role: network/flannel, when: network == 'flannel', tags: network }

- hosts: masters
  become: yes
  roles:
    - { role: kubernetes/ha, tags: ha }
    - { role: kubernetes/master, tags: master }

- hosts: nodes
  become: yes
  roles:
    - { role: kubernetes/node, tags: node }

- hosts: cluster
  become: yes
  roles:
   - { role: network/calico, when: network == 'calico', tags: network }
