---

- hosts: sslhost
  gather_facts: no
  become: yes
  roles:
    - { role: sslcert, tags: sslcert }

- hosts: etcd
  become: yes
  roles:
   - { role: etcd, tags: etcd }

- hosts: cluster
  gather_facts: no
  become: yes
  roles:
    - { role: docker, tags: docker }

- hosts: masters
  become: yes
  roles:
    - { role: kubernetes/ha, tags: ha }
    - { role: kubernetes/master, tags: master }

- hosts: nodes
  become: yes
  roles:
    - { role: kubernetes/node, tags: node }

- hosts: masters
  gather_facts: no
  become: yes
  roles:
    - { role: cni, tags: cni }
