---
- name: Enable the shared IP address variable
  shell: "{{ item }}"
  with_items:
    - "echo 'net.ipv4.ip_nonlocal_bind=1' > /etc/sysctl.conf"
    - "sysctl -p"

- name: Create kubernetes manifests config directory
  file: path={{ manifest_config_dir }} state=directory

- name: Copy keepalived yaml config file
  template: src="keepalived.yml.j2" dest={{ manifest_config_dir }}/keepalived.yml

- name: Create haproxy config directory
  file: path={{ haproxy_dir }} state=directory

- name: Copy haproxy yml config file
  template: src="haproxy.yml.j2" dest={{ manifest_config_dir }}/haproxy.yml

- name: Copy haproxy config file
  template: src="haproxy.cfg.j2" dest={{ haproxy_dir }}/haproxy.cfg
