---
- name: Create calico bin directory
  file: path="{{ cni_bin_dir }}" state=directory

- name: Download calico plugins
  get_url:
    url: "{{ calico_download_url }}/{{ item }}"
    dest: "{{ cni_bin_dir }}"
    validate_certs: False
    owner: root
    mode: 0755
  with_items:
    - calico
    - calico-ipam
  register: calico_download

- name: Download calico ctl tool
  get_url:
    url: "{{ calicoctl_download_url }}"
    dest: "/usr/bin/"
    validate_certs: False
    owner: root
    mode: 0755
  delegate_to: "{{ groups['masters'][0] }}"
  register: calicoctl_download

- name: Check cni plugin tgz file already exists
  stat:
    path: "{{ tmp_dir }}/cni-amd64-v{{ cni_version }}.tgz"
  register: check_cni

- name: Download cni plugin tgz file
  when: not check_cni.stat.exists
  get_url:
    url: "{{ cni_download_url }}"
    dest: "{{ tmp_dir }}"
    validate_certs: False
  register: cni_download

- name: Extract cni plugin tgz file to cni bin
  when: cni_download|succeeded
  unarchive:
    src: "{{ tmp_dir }}/cni-amd64-v{{ cni_version }}.tgz"
    dest: "{{ cni_bin_dir }}"
    copy: no
    owner: root
    mode: 0755
