---

- name: Reset SSL cert
  when: sslcert|default(false)
  include: sslcert.yml

- name: Reset Kubernetes  cluster
  when: kube|default(false)
  include: kube.yml

- name: Reset Etcd cluster
  when: etcd|default(false)
  include: etcd.yml

- name: Reset Docker registry cluster
  when: registry|default(false)
  include: registry.yml
