---

- name: Stop all component systemd service
  ignore_errors: True
  systemd: name={{ item }} state=stopped enabled=no
  with_items:
    - docker.service
    - docker.socket

- name: Delete Docker systemd service file
  ignore_errors: True
  file: path="{{ systemd_dir }}/{{ item }}" state=absent
  with_items:
    - docker.service
    - docker.socket

- name: Delete Docker container and registry data
  ignore_errors: True
  file: path="{{ item }}" state=absent
  with_items:
    - /var/lib/registry
    - /var/lib/docker/containers
    - /var/lib/docker/vfs/dir
