---
- name: Restart docker engine
  command: /bin/true
  notify:
    - Check docker existence
    - Stop docker engine
    - Delete docker0 interface
    - Start docker engine

- name: Check docker existence
  command: "docker version"
  register: has_docker
  changed_when: false
  failed_when: false

- name: Stop docker engine
  service: name=docker state=stopped

- name: Delete docker0 interface
  command: ip link delete docker0
  when: '"docker0" in ansible_interfaces'

- name: Start docker engine
  service: name=docker state=started
