---
- name: Adding EPEL repository
  yum:
    name: epel-release
    state: latest

- name: Adding Docker yum repository
  yum_repository:
    name: Docker
    description: Docker Repository
    file: docker
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://yum.dockerproject.org/gpg

- name: Adding Kubernetes yum repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes Repository
    file: kubernetes
    baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: no

- name: Adding Ceph yum repository
  when: ceph_cluster
  yum_repository:
    name: "ceph-{{ ceph_version }}"
    description: Ceph Repository
    file: ceph
    baseurl: "https://download.ceph.com/rpm-{{ ceph_version }}/el7/x86_64"
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.ceph.com/keys/release.asc
