---
- name: Adding EPEL repository
  when: docker_install_type == "binary"
  yum: name=epel-release state=present

- name: Adding Docker yum repository
  when: docker_install_type == "binary"
  yum_repository:
    name: Docker
    description: Docker Repository
    file: docker
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://yum.dockerproject.org/gpg

- name: Adding Kubernetes yum repository
  when: kube_install_type == "binary"
  yum_repository:
    name: Kubernetes
    description: Kubernetes Repository
    file: kubernetes
    baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: no
