---
- name: Install etcd key/value store
  include: source.yml

- name: Setup etcd systemd service
  include: systemd.yml

- name: Configure etcd key/value store
  include: config.yml

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Enable and restart etcd
  service: name=etcd enabled=yes state=restarted
  register: etcd_started
