---
# - name: Install etcd (RHEL/CentOS)
#   when: ansible_os_family == "RedHat"
#   yum: name=etcd state=latest
#
# - name: Install etcd (Debian/Ubuntu)
#   when: ansible_os_family == "Debian"
#   apt: name=etcd state=latest

- name: Install etcd
  include: git-install.yml

- name: Setup flannel systemd service
  include: systemd.yml

- name: Prepare and write etcd configuration
  include: config.yml

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Enable and restart etcd
  service: name=etcd enabled=yes state=restarted
  register: etcd_started
