---
## Install some package tasks

- name: Install list of packages (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  apt: name={{item}} state=latest
  with_items:
      - openvswitch-switch
      - bridge-utils
      - git

- name: Install list of packages (CentOS/RHEL)
  when: ansible_os_family == "RedHat"
  yum: name={{item}} state=latest
  with_items:
      - vim

- name: Download docker engine installer
  get_url: url=https://get.docker.com/  dest=/tmp/docker-installer.sh

- name: Execute the script to install docker engine
  script: /tmp/docker-installer.sh
  notify: Starting docker engine service.
