---

- name: "Check {{ img.name }} image already exists"
  when: img is defined
  shell: "docker images | grep -o '{{ img.repos }}{{ img.name }}' | wc -l"
  run_once: true
  ignore_errors: True
  register: check_image

- name: "Pull {{ img.name }} image"
  when: img is defined and check_image.stdout|int <= 0
  shell: |
    docker pull {{ img.repos }}{{ img.name }}:{{ img.tag }}
  register: pull_result
  until: pull_result|succeeded
  retries: 4

- name: "Archive {{ img.name }} image"
  when:
    - archive|default(false)
    - pull_result|succeeded or check_image.stdout|int > 0
  shell: |
    docker save {{ img.repos }}{{ img.name }}:{{ img.tag }} \
                > {{ image_tmp }}/{{ img.name }}-image.tar
  register: archive_image

- name: "Tag push {{ img.name }} image"
  when:
    - push|default(false)
    - pull_result|succeeded or check_image.stdout|int > 0
  shell: |
    docker tag {{ img.repos }}{{ img.name }}:{{ img.tag }} \
               {{ item }}/{{ img.name }}:{{ img.tag }}
  with_items: "{{ insecure_registrys }}"
  register: tag_image

- name: "Push {{ img.name }} image to registry"
  when:
    - tag_image
    - push|default(false)
    - pull_result|succeeded or check_image.stdout|int > 0
  shell: "docker push {{ item }}/{{ img.name }}:{{ img.tag }}"
  with_items: "{{ insecure_registrys }}"
  register: push_image

- name: "Remove {{ img.name }} image tag"
  when:
    - push_image
    - push|default(false)
    - pull_result|succeeded or check_image.stdout|int > 0
  shell: "docker rmi {{ item }}/{{ img.name }}:{{ img.tag }}"
  with_items: "{{ insecure_registrys }}"
  register: remove_image
