---
- name: Check kubelet service already exists
  stat: path="{{ service_dir }}/kubelet.service"
  register: check_kubelet_service

- name: Stop systemd service and upgrade component file
  when: check_kubelet_service.stat.exists
  service: name=kubelet enabled=yes state=stopped

- name: Install Kubernetes from binary release
  when: install_type == "pkg"
  include: package.yml

- name: Install Kubernetes from source release
  when: install_type == "src"
  include: source.yml

- name: Configure kubernetes component
  include: config.yml

- name: Add extra authenticating
  when: extra_auth is defined
  include: auth.yml

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Enable and restart kubelet
  service: name=kubelet enabled=yes state=restarted
  register: kubelet_start

- name: Wait for apiserver start
  when: kubelet_start
  wait_for:
    host: "127.0.0.1"
    port: "8080"
    connect_timeout: 5
    state: started
