---

- name: Check kubelet service already exists
  stat: path="{{ systemd_dir }}/kubelet.service"
  register: check_kubelet_service

- name: Stop kubelet systemd service to upgrade
  when: check_kubelet_service.stat.exists
  service: name=kubelet enabled=yes state=stopped

- name: Configure Kubernetes component
  include: config.yml

- name: Add Kubernetes extra authentication
  when: extra_auth is defined
  include: auth.yml

- name: Init kubelet systemd service
  include: systemd.yml

- name: Enable and restart kubelet engine
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes
  notify:
    - Wait for apiserver start
    - Wait for controller start
    - Wait for schedule start
