---
- name: Create kubernetes release directory
  file: path="{{ kube_dir }}" state=directory

- name: Check kubelet component file
  stat: path="{{ kube_dir }}/kubelet"
  register: check_kubelet

- name: Check kubelet component version is match
  when: check_kubelet.stat.exists
  shell: "{{ kube_dir }}/kubelet --version | grep -o '[0-9.]*'"
  register: check_kube_version

- name: Download kubernetes component files
  when: not check_kubelet.stat.exists or check_kube_version.stdout != kube_version
  get_url: url="{{ kube_download_url }}/{{ item }}" dest="{{ kube_dir }}" mode=0755
  with_items:
    - kubectl
    - kubelet
  register: kube_download

- name: Create kubernetes component symlinks
  file:
    src: "{{ kube_dir }}/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
    force: yes
  with_items:
    - kubectl
    - kubelet
