---
- name: Download flannel tar file
  get_url:
    url: "{{ flannel_download_url }}"
    dest: "/tmp"
    validate_certs: False
  register: flannel_download

- name: Create flannel release directory
  when: flannel_version != "0.5.5"
  file: path="{{ flannel_dir }}/flannel-{{ flannel_version }}" state=directory

- name: Extract flannel tar file (0.5.5)
  when:
    - flannel_download|succeeded
    - flannel_version == "0.5.5"
  unarchive:
    src: "/tmp/flannel-{{ flannel_version_uri }}-linux-amd64.tar.gz"
    dest: "{{ flannel_dir }}"
    copy: no

- name: Extract flannel tar file (0.6.0+)
  when:
    - flannel_download|succeeded
    - flannel_version != "0.5.5"
  unarchive:
    src: "/tmp/flannel-{{ flannel_version_uri }}-linux-amd64.tar.gz"
    dest: "{{ flannel_dir }}/flannel-{{ flannel_version }}"
    copy: no

- name: Create flannel symlinks
  file:
    src: "{{ flannel_dir }}/flannel-{{ flannel_version }}/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
    force: yes
  with_items:
    - flanneld
    - mk-docker-opts.sh
