---
- name: Install flannel
  when: ansible_os_family == "RedHat"
  yum:
    name: flannel
    state: latest
    update_cache: yes

- name: Prepare and write flannel configuration to etcd
  include: config.yml

- name: Copy etcd certificate from ansible host
  when: etcd_peer_url_scheme == 'https'
  copy: src={{ master_cert_dir }} dest={{ kube_config_dir }}
  register: etcd_cert

- name: Enable flannel on node
  when: change_flannel|succeeded
  service: name=flanneld enabled=yes

- name: Start flannel on node
  when: change_flannel|changed or etcd_cert|changed
  service: name=flanneld state=started
  register: flannel_started
  notify:
     - Restart docker engine
