---
- name: Install flannel
  include: git-install.yml

- name: Prepare and write flannel configuration to etcd
  include: config.yml

- name: Copy etcd certificate from ansible host
  when: etcd_peer_url_scheme == 'https'
  copy: src={{ master_cert_dir }} dest={{ kube_config_dir }}
  register: etcd_cert

- name: Reload flannel systemd daemon
  sudo: yes
  command: systemctl daemon-reload

- name: Enable and restart flannel
  when: change_flannel|succeeded
  service: name=flanneld enabled=yes state=restarted
  register: flannel_started
