---
- name: Download sigil tar file
  get_url:
    url: "{{ sigil_download_url }}"
    dest: "/tmp"
    validate_certs: False
  register: sigil_download

- name: Extract sigil tar file
  when:
    - sigil_download|succeeded
  unarchive:
    src: "/tmp/sigil_{{ sigil_verison }}_Linux_x86_64.tgz"
    dest: "{{ bin_dir }}"
    copy: no

- name: Install Ceph packages (RHEL/CentOS)
  when: ansible_os_family == "RedHat"
  yum: name=ceph state=present

- name: Install Ceph packages (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  apt: name=ceph state=present
