---

- name: Configure Flannel network plugin
  include: config.yml

- name: Init Flannel network systemd service
  include: systemd.yml

- name: Enable and restart Flannel network
  systemd:
    name: flanneld
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_flannel

- name: Enable and restart Docker engine
  when: started_flannel|succeeded
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Wait for repository server start
  when: repos_offline
  uri:
    url: "{{ repos_offline_url }}"
    validate_certs: no
  register: result
  until: result.status == 200 or result.status == 401
  retries: 10
  delay: 5
  delegate_to: "{{ groups['repos'][0] }}"
  run_once: true
