---
- name: Install Kubernetes packages (RHEL/CentOS)
  when: ansible_os_family == "RedHat"
  yum:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    -  kubelet
    -  kubernetes-cni
  register: nodepackage

- name: Install Kubernetes packages (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    -  kubelet
    -  kubernetes-cni
  register: nodepackage

- name: Create and copy node config file
  include: config.yml

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Enable and restart kubelet
  service: name=kubelet enabled=yes state=restarted
  register: kubelet_start_node
