---
- name: Install Kubernetes Node packages
  when: ansible_os_family == "RedHat"
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    -  kubelet
    -  kubernetes-cni
  register: nodepackage

- name: Create and copy node config file
  include: config.yml

- name: Start and enable kubelet on node
  service: name=kubelet enabled=no state=started
  register: kubelet_start_node

- name: Reload kubelet
  when: create_ssl_cert|changed or kubelet|changed or kubeletconfig|changed
  service: name=kubelet state=restarted
