---
- name: Kubernetes from binary release
  when: kube_install_type == "package"
  include: package.yml

- name: Kubernetes from source release
  when: kube_install_type == "source"
  include: source.yml

- name: Create and copy node config file
  include: config.yml

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Enable and restart kubelet
  service: name=kubelet enabled=yes state=restarted
  register: kubenode_start
