---
## Install some package tasks
- name: Install list of packages (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  apt: name={{item}} state=latest
  with_items:
      - openvswitch-switch
      - bridge-utils
      - git

- name: Install list of packages (CentOS/RHEL)
  when: ansible_os_family == "RedHat"
  yum: name={{item}} state=latest
  with_items:
      - vim
      - bridge-utils
      - git
