---
- name: Create cni network config directory
  file: path="{{ cni_config_dir }}" state=directory

- name: Copy calico cni plugin config
  template: src=10-calico.conf.j2 dest="{{ cni_config_dir }}/10-calico.conf"

- name: Create kubernetes network config directory
  file: path="{{ kube_network_dir }}" state=directory

- name: Copy calico policy controller yml
  template: src=policy-controller.yml.j2 dest="{{ kube_network_dir }}/policy-controller.yml"

- name: Check the calico policy controller
  shell: "kubectl get pods --all-namespaces=true | grep calico-policy-controller"
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  register: check_calico
  ignore_errors: True

- name: Install the calico policy controller
  when: check_calico|failed
  shell: "kubectl create --kubeconfig={{ kubeadmin_config }} -f {{ kube_network_dir }}/policy-controller.yml"
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
