---
- name: Install calico network
  include: source.yml

- name: Setup calico systemd service
  include: systemd.yml

- name: Configure calico plugin
  include: config.yml

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Enable and restart calico network
  when: change_calico|succeeded
  systemd:
    name: calico-node
    daemon_reload: yes
    state: started
    enabled: yes
  register: calico_started
