---
# Prepare configuration files
- name: Create kubernetes config directory
  file: path={{ manifest_config_dir }} state=directory

- name: Create weave directory
  when: weave_net
  file: path={{ weave_dir }} state=directory

- name: Copy weave file
  when: weave_net
  copy: src=10-weave.conf  dest=/etc/cni/net.d/10-weave.conf

- name: Copy apiserver config file
  template: src="kube-apiserver.json.j2" dest={{ manifest_config_dir }}/kube-apiserver.json

- name: Copy controller-manager config file
  template: src="kube-controller-manager.json.j2" dest={{ manifest_config_dir }}/kube-controller-manager.json

- name: Copy scheduler config file
  template: src="kube-scheduler.json.j2" dest={{ manifest_config_dir }}/kube-scheduler.json

- name: Copy kubeadmin config file
  template: src="admin.conf.j2" dest={{ kubeadmin_config }}

- name: Copy openssl certificate from ansible host
  copy: src={{ master_cert_dir }} dest={{ kube_config_dir }}

- name: Copy kubelet config file
  template: src="kubelet.j2" dest={{ kube_config_dir }}/kubelet

- name: Copy kubelet service file
  copy: src=kubelet.service dest={{ service_dir }}/kubelet.service owner=root group=root mode=0755

- name: Create kubelet directory
  file: path=/var/lib/kubelet state=directory
