---
- name: Install Kubernetes packages (RHEL/CentOS)
  when: ansible_os_family == "RedHat"
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    -  kubectl
    -  kubelet
    -  kubernetes-cni
  register: masterpackage

- name: Install Kubernetes packages (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    -  kubectl
    -  kubelet
    -  kubernetes-cni
  register: masterpackage

- name: Create and copy master config file
  include: config.yml

- name: Reload docker systemd daemon
  sudo: yes
  command: systemctl daemon-reload

- name: Enable and restart kubelet
  service: name=kubelet enabled=yes state=restarted
  register: kubelet_start
