---
- name: Install Kubernetes packages
  when: ansible_os_family == "RedHat"
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    -  kubectl
    -  kubelet
    -  kubernetes-cni
  register: masterpackage

- name: Create and copy master config file
  include: config.yml

- name: Start and enable kubelet
  service: name=kubelet enabled=no state=started
  register: kubelet_start

- name: Reload kubelet
  when: openssl_cert|changed or kubelet_service|changed or kubelet_conf|changed
  service: name=kubelet state=restarted
