# Etcd common vars
etcd_version: 3.1.6 # etcd version, support 2.1.0+

etcd_client_port: 2379
etcd_peer_port: 2380
etcd_peers_group: etcd
etcd_initial_cluster_state: new
etcd_initial_cluster_token: etcd-k8s-cluster
etcd_interface: ""
etcd_machine_address: "{% if etcd_interface != '' %}{{ hostvars[inventory_hostname]['ansible_' + etcd_interface].ipv4.address }}
{%- else %}{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}{% endif %}"
etcd_initial_advertise_peer_urls: "{{ etcd_peer_url_scheme }}://{{ etcd_machine_address }}:{{ etcd_peer_port }}"
etcd_listen_peer_urls: "{{ etcd_peer_url_scheme }}://0.0.0.0:{{ etcd_peer_port }}"
etcd_advertise_client_urls: "{{ etcd_peer_url_scheme }}://{{ etcd_machine_address }}:{{ etcd_client_port }}"
etcd_listen_client_urls: "{{ etcd_peer_url_scheme }}://0.0.0.0:{{ etcd_client_port }}"

# Etcd dir vars
etcd_conf_dir: /etc/etcd
etcd_data_dir: /var/lib/etcd
etcd_releases_dir: /opt/etcd

# The default url to download the etcd tar from
etcd_base_url: "https://github.com/coreos/etcd/releases/download"
etcd_download_url: "{{ etcd_base_url }}/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
