---
- name: Install docker engine (RHEL/CentOS)
  when:
    - ansible_os_family == "RedHat"
    - docker_source_type == "package-manager"
  yum: name=docker-engine state=present

- name: Install docker engine (Debian/Ubuntu)
  when:
    - ansible_os_family == "Debian"
    - docker_source_type == "package-manager"
  apt: name=docker-engine state=present

- name: Install docker engine from source
  when: docker_source_type == "git-release"
  include: git-install.yml

- name: Setup docker systemd service
  include: systemd.yml

- name: Fix docker 1.13.0+ forward issue
  command: iptables -P FORWARD ACCEPT

- name: Add any insecure registrys to docker config
  lineinfile: dest={{ config_dir }}/docker regexp=^INSECURE_REGISTRY= line=INSECURE_REGISTRY="{% for reg in insecure_registrys %}--insecure-registry={{ reg }} {% endfor %}"
  when:
    - insecure_registrys is defined and insecure_registrys > 0

- name: Add registry to docker config
  lineinfile: dest={{ config_dir }}/docker regexp=^ADD_REGISTRY= line=ADD_REGISTRY="{% for reg in add_registry %}--add-registry={{ reg }} {%endfor %}"
  when:
    - add_registry is defined and add_registry > 0

- name: Reload systemd daemon
  command: systemctl daemon-reload
  notify:
    - Stop docker engine service
    - Delete docker0 interface
    - Enable and restart docker socket
    - Enable and restart docker
