---
- name: Install docker engine (RHEL/CentOS)
  when: ansible_os_family == "RedHat"
  yum: name=docker-engine-1.12.6-1.el7.centos state=present

- name: Install docker engine (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  apt: name=docker-engine=1.12.6-0~ubuntu-xenial state=present

- name: Add any insecure registrys to docker config
  lineinfile: dest={{ config_dir }}/docker regexp=^INSECURE_REGISTRY= line=INSECURE_REGISTRY="{% for reg in insecure_registrys %}--insecure-registry={{ reg }} {% endfor %}"
  when:
    - insecure_registrys is defined and insecure_registrys > 0

- name: Add registry to docker config
  lineinfile: dest={{ config_dir }}/docker regexp=^ADD_REGISTRY= line=ADD_REGISTRY="{% for reg in add_registry %}--add-registry={{ reg }} {%endfor %}"
  when:
    - add_registry is defined and add_registry > 0

- name: Override docker service file directory for Debian
  when: ansible_os_family == "Debian"
  set_fact:
    docker_service_dir: "/lib/systemd/system"

- name: Add docker service file
  template: src="docker.service.j2" dest={{ docker_service_dir }}/docker.service owner=root group=root mode=0755

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Enable and restart docker
  service: name=docker enabled=yes state=restarted
