---
- name: Install docker engine from package
  when: install_type == "pkg"
  include: package.yml

- name: Install docker engine from source
  when: install_type == "src"
  include: source.yml

- name: Setup docker systemd service
  include: systemd.yml

- name: Add any insecure registrys to docker config
  lineinfile: dest={{ env_config_dir }}/docker regexp=^INSECURE_REGISTRY= line=INSECURE_REGISTRY="{% for reg in insecure_registrys %}--insecure-registry={{ reg }} {% endfor %}"
  when:
    - insecure_registrys is defined and insecure_registrys > 0

- name: Add registry to docker config
  lineinfile: dest={{ env_config_dir }}/docker regexp=^ADD_REGISTRY= line=ADD_REGISTRY="{% for reg in add_registry %}--add-registry={{ reg }} {%endfor %}"
  when:
    - add_registry is defined and add_registry > 0

- name: Reload systemd daemon
  command: systemctl daemon-reload
  notify:
    - Stop docker engine service
    - Delete docker0 interface
    - Enable and start docker socket
    - Enable and restart docker
