---
- name: Check docker version not latest
  when: docker_version == 'latest'
  fail: msg="The source install type not support 'latest' version tag."

- name: Check docker tar file already exists
  stat:
    path: "/tmp/docker-{{ docker_version }}.tgz"
  register: check_docker

- name: Download docker tar file
  when: not check_docker.stat.exists
  get_url:
    url: "{{ docker_download_url }}"
    dest: "/tmp"
    validate_certs: False
  register: docker_download

- name: Extract docker tar file to bin
  when: docker_download|succeeded
  unarchive:
    src: "/tmp/docker-{{ docker_version }}.tgz"
    dest: "/usr/bin/"
    copy: no
    extra_opts: ['--strip-components=1']
