---
- name: Create cni network config directory
  file: path="{{ cni_etc_dir }}" state=directory

- name: Copy Calico cni plugin config
  template:
    src: 10-calico.conf.j2
    dest: "{{ cni_etc_dir }}/10-calico.conf"

- name: Copy Etcd certificate from ansible host
  when: etcd_peer_url_scheme == 'https'
  copy: src={{ cert_dir }} dest={{ kube_etc_dir }}

- name: Create kubernetes network config directory
  file: path="{{ kube_network_dir }}" state=directory

- name: Copy Calico policy controller yml
  template:
    src: policy-controller.yml.j2
    dest: "{{ kube_network_dir }}/policy-controller.yml"
  delegate_to: "{{ groups['masters'][0] }}"

- name: Check the Calico policy controller
  shell: "kubectl get pods --all-namespaces=true | grep calico-policy-controller"
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  register: check_calico
  ignore_errors: True

- name: Create the Calico policy controller
  when: check_calico|failed
  shell: "kubectl create --kubeconfig={{ kubeadmin_config }} -f {{ kube_network_dir }}/policy-controller.yml"
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true

- name: Create Calicoctl network symlinks
  file:
    src: "{{ downloads.calicoctl.dir }}/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
    force: yes
  with_items:
    - calicoctl
