---

- name: Configure Calico network plugin
  include: config.yml

- name: Init Calico systemd service
  include: systemd.yml

- name: Enable and restart Calico network
  when: change_calico|succeeded
  systemd:
    name: calico-node
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_calico
