---

- name: Copy Calico default environment file
  template:
    src: calico-node.j2
    dest: "{{ system_env_dir }}/calico-node"

- name: Copy Calico-node systemd service file
  template:
    src: calico-node.service.j2
    dest: "{{ systemd_dir }}/calico-node.service"
  register: change_calico
