---
# Update kubernetes nodes.

- hosts: "{{ nodes }}"
  become: yes
  vars_prompt:
    - name: "nodes"
      prompt: "Which nodes would you like to setup?"
      private: no
  roles:
    - { role: docker, tags: docker }
    - { role: kubernetes/node, tags: node }
    - { role: networking/flannel, when: networking == 'flannel', tags: flannel }
    - { role: networking/calico, when: networking == 'calico', tags: calico }
