---
# Terminate kubernetes addons

- hosts: masters
  gather_facts: no
  become: yes
  tags: del-addons
  vars:
    admin_config: /etc/kubernetes/admin.conf
    addon_dir: /etc/kubernetes/addon/
  tasks:
    - name: Delete all kubernetes addons
      shell: "kubectl delete --kubeconfig={{ admin_config }} -f {{ addon_dir }}"
      delegate_to: "{{ groups['masters'][0] }}"
      run_once: true
      ignore_errors: True
