---

- hosts: registry
  gather_facts: no
  become: yes
  roles:
    - { role: docker, tags: docker }

- hosts: registry
  gather_facts: no
  become: yes
  roles:
    - { role: registry, tags: registry, enable_ui: false }
