---
- name: Create flannel release directory
  file: path="{{ flannel_dir }}" state=directory

- name: Check flannel tar file already exists
  stat:
    path: "/tmp/{{ flannel_tar_name }}"
  register: check_flannel

- name: Download flannel tar file
  when: not check_flannel.stat.exists
  get_url:
    url: "{{ flannel_download_url }}"
    dest: "/tmp"
    validate_certs: False
  register: flannel_download

- name: Extract flannel tar file (0.5.5)
  when:
    - flannel_download|succeeded
    - flannel_version == "0.5.5"
  unarchive:
    src: "/tmp/{{ flannel_tar_name }}"
    dest: "{{ flannel_dir }}"
    copy: no
    extra_opts: ['--strip-components=1']

- name: Extract flannel tar file (0.6.0+)
  when:
    - flannel_download|succeeded
    - flannel_version != "0.5.5"
  unarchive:
    src: "/tmp/{{ flannel_tar_name }}"
    dest: "{{ flannel_dir }}"
    copy: no

- name: Create flannel symlinks
  file:
    src: "{{ flannel_dir }}/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
    force: yes
  with_items:
    - flanneld
    - mk-docker-opts.sh
