---
# Ceph cluster on Kubernetes

ceph_image_tag: "tag-build-master-kraken-ubuntu-16.04"

osd_cluster_network: "{{ pod_network_cidr }}"
osd_public_network: "{{ osd_cluster_network }}"

sigil_verison: 0.4.0
sigil:
  name: sigil
  description: "sigil tool"
  dir: /opt/sigil
  url: "https://github.com/gliderlabs/sigil/releases/download/v{{ sigil_verison }}/"
  items: [ "sigil_{{ sigil_verison }}_Linux_x86_64.tgz" ]
  unarchive:
    extra_opt: "['--strip-components=0']"
